# Generated by Django 4.2.5 on 2023-10-10 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_task_timeschedule_task_timefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeField',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
