# Generated by Django 4.2.5 on 2023-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_timefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeTotal',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
