# Generated by Django 4.2.5 on 2023-10-10 14:35

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_task_timetotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeTotal',
            field=models.IntegerField(blank=True, default=django.db.models.aggregates.Sum('timeField.all()'), null=True),
        ),
    ]
