# Generated by Django 4.2.5 on 2023-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_timeschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timeSchedule',
        ),
        migrations.AddField(
            model_name='task',
            name='timeField',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
