# Generated by Django 4.2.5 on 2023-10-10 13:58

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_remove_task_timetotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.db.models.aggregates.Sum('timeField')),
        ),
    ]
