# Generated by Django 4.2.5 on 2023-10-11 06:50

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_task_timetotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.db.models.aggregates.Sum('timeField')),
        ),
    ]
