# Generated by Django 4.2.5 on 2023-10-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_remove_task_timetotal_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeField',
            field=models.IntegerField(null=True),
        ),
    ]
