# Generated by Django 4.2.5 on 2023-10-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_task_minutes_alter_task_timefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeField',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
